version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name lastkadai-app --s3-location s3://lastkadai-s3bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src